# docker-compose.yml
version: '3'
services:
  frontend:
    build:
      context: ./front
    image: kiurow590/front:v1.0  # Nom de l'image pour Docker Hub
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    build:
      context: ./back
    image: kiurow590/back:v1.0  # Nom de l'image pour Docker Hub
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production

networks:
  app-network:
    driver: bridge
